"""
Trains a tiny 2-4-1 neural network (tanh hidden, sigmoid output) that maps
  [ambient light (0..1), occupancy (0/1)]  ->  LED brightness (0..1)
and exports the weights as a C header for the Arduino firmware.

Run:  python train_model.py
Out:  ../firmware/ai_adaptive_led/model_weights.h
"""
import numpy as np

rng = np.random.default_rng(42)

# ---------- 1. Build training data ----------
# The "teacher" behaviour: when the room is occupied, the darker it is the
# brighter the LED should glow; above ~80 % ambient light the LED stays off.
N = 4000
light = rng.uniform(0.0, 1.0, N)
occ = rng.integers(0, 2, N).astype(float)
target = occ * np.clip((0.8 - light) / 0.8, 0.0, 1.0)
target = np.clip(target + rng.normal(0, 0.02, N), 0.0, 1.0)   # sensor-style noise

X = np.stack([light, occ], axis=1)
y = target.reshape(-1, 1)

# ---------- 2. Network ----------
H = 4
W1 = rng.normal(0, 0.8, (2, H)); b1 = np.zeros(H)
W2 = rng.normal(0, 0.8, (H, 1)); b2 = np.zeros(1)
sigmoid = lambda z: 1.0 / (1.0 + np.exp(-z))

lr = 0.5
for epoch in range(6000):
    h = np.tanh(X @ W1 + b1)
    out = sigmoid(h @ W2 + b2)
    err = out - y
    d_out = err * out * (1 - out) / N
    dW2 = h.T @ d_out;  db2 = d_out.sum(0)
    d_h = (d_out @ W2.T) * (1 - h ** 2)
    dW1 = X.T @ d_h;    db1 = d_h.sum(0)
    W1 -= lr * dW1; b1 -= lr * db1; W2 -= lr * dW2; b2 -= lr * db2
    if epoch % 1000 == 0:
        print(f"epoch {epoch:5d}  MSE = {np.mean(err**2):.5f}")

pred = sigmoid(np.tanh(X @ W1 + b1) @ W2 + b2)
print(f"final MSE = {np.mean((pred - y)**2):.5f}   MAE = {np.mean(np.abs(pred - y)):.4f}")

# ---------- 3. Export ----------
def arr(a):
    return ", ".join(f"{v:.6f}f" for v in np.ravel(a))

with open("../firmware/ai_adaptive_led/model_weights.h", "w") as f:
    f.write("// Auto-generated by training/train_model.py - do not edit by hand\n")
    f.write("#pragma once\n#include <avr/pgmspace.h>\n\n")
    f.write(f"#define N_HIDDEN {H}\n")
    f.write(f"const float W1[{H}][2] PROGMEM = {{\n")
    for j in range(H):
        f.write(f"  {{ {W1[0, j]:.6f}f, {W1[1, j]:.6f}f }},\n")
    f.write("};\n")
    f.write(f"const float B1[{H}] PROGMEM = {{ {arr(b1)} }};\n")
    f.write(f"const float W2[{H}] PROGMEM = {{ {arr(W2)} }};\n")
    f.write(f"const float B2 PROGMEM = {b2[0]:.6f}f;\n")

np.savetxt("../tests/reference.csv",
           [[l, o, float(sigmoid(np.tanh(np.array([l, o]) @ W1 + b1) @ W2 + b2)[0])]
            for l in (0.05, 0.2, 0.4, 0.6, 0.85) for o in (0, 1)],
           delimiter=",", fmt="%.6f")
print("weights exported.")
