// Auto-generated by training/train_model.py - do not edit by hand
#pragma once
#include <avr/pgmspace.h>

#define N_HIDDEN 4
const float W1[4][2] PROGMEM = {
  { 1.566240f, -1.649108f },
  { 0.456874f, 0.978641f },
  { -0.399020f, 0.528820f },
  { 1.464630f, -1.170442f },
};
const float B1[4] PROGMEM = { 0.721344f, 0.014215f, -0.337995f, 0.506263f };
const float W2[4] PROGMEM = { -2.358239f, 0.069147f, 0.688261f, -2.021883f };
const float B2 PROGMEM = -0.886549f;
